### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by madun** [ihfazhillah/shamelaws_books_download#1]
Hallo sir, how to run this repo

**Comment by ihfazhillah** [comment]
Hi @madun , I create this script long time ago, and I don't know if it still work or not now. 

As I can see from my script, there are some dependencies that you should install first:
1. beautifulsoup , you can refer to this page https://www.crummy.com/software/BeautifulSoup/bs4/doc/
2. wget https://pypi.org/project/wget/

Then just open the `download.py` and run it. 

Let me know if you still need further assistance.

**Comment by madun** [comment]
thank you sir
